### ISSUE TITLE
Support iOS version lower than iOS 15

### ISSUE THREAD

**Issue by michalkoch** [lucacivale/Maui.BottomSheet#10]
Hello,
I would like to ask what are the restrictions for iOS lower than iOS 15? Or why iOS version lower than 15 is not supported? 

Thank you, Michal.

**Comment by lucacivale** [comment]
@michalkoch iOS 15 introduced the `UISheetPresentationController` to present a Sheet. Without the controller we can't present a Sheet without building everything ourself.
So I don't think support for iOS 14 and lower will be added by myself(feel free to create a PR).
