### ISSUE TITLE
Closed event call just after the BottomSheet is already closed

### ISSUE THREAD

**Issue by adrianotrentim** [lucacivale/Maui.BottomSheet#11]
I am having problems using the component with the following situation.

I'm using the component to create a menu, as an option to ToolBarItem, since iOS doesn't render these menus correctly like Android.

The problem is that when I execute a command from this menu, I want the BottomSheet to be closed, and call a certain action.

In this action, I have a call to a popup that displays a loading frame.

The problem is that, when calling this popup, it is shown over the BottomSheet. And I even understand why, since it is a View.

I tried using this command call within the BottomSheet's Closed event, but this event is called when the BottomSheet is still present on the screen.

Is there any possibility of the Closed event being called when the BottomSheet is already closed?

**Comment by lucacivale** [comment]
Can you give me a repro for that?

**Comment by adrianotrentim** [comment]
Take a look at PR 12 and see if you agree

**Comment by adrianotrentim** [comment]
but if you want to simulate do the following.
1 - Create a project, add CommunityToolKit
2 - Create a page and add the BottomSheet with a button inside, linked to any command on the page.
3 - In this command, create a CommunityToolkit popup, to load it in the same command. You will notice that the popup will be "inside" the BottomSheet.

To prevent this, create an event in the Closed of the BottomSheet, that is, so that when closing, the popup is called within the page, no longer within the BottomSheet.

This would be the logic, but it doesn't work, because the Closed event is called when the BottomSheed is still visible

**Comment by adrianotrentim** [comment]
forgive my English, I'm Brazilian and I don't speak English very well

**Comment by lucacivale** [comment]
@adrianotrentim thank you for your PR. This should be fixed and I'll release a new version asap.
