### ISSUE TITLE
iOS FromContentPage doesn't respect content page's background color

### ISSUE THREAD

**Issue by edgiardina** [lucacivale/Maui.BottomSheet#7]
**Describe the bug**
When using a bottom sheet derived `FromContentPage`, the bottomsheet respects the backgroundcolor of the ContentPage in Android, but in iOS does not. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS 17.2 iPhone 15

**Comment by lucacivale** [comment]
Can you please share a repro? I'll take care of the issue.

**Comment by edgiardina** [comment]
it would take a little time to put together a reproduction repo. My project is OSS and this branch has the cahnges
https://github.com/edgiardina/IfpaMaui/tree/bottom-sheet
But it requires an API key which is not committed to the repo to run that project.

Specific invocation: 
https://github.com/edgiardina/IfpaMaui/blob/bottom-sheet/ViewModels/TournamentResultsViewModel.cs#L36

Background color of the content page:
https://github.com/edgiardina/IfpaMaui/blob/bottom-sheet/Views/TournamentInfoPage.xaml
